## リザバーコンピューティング
参考：\
「リザバーコンピューティング 時系列パターン認識のための高速機械学習の理論とハードウェア 田中剛平・中根了昌・廣瀬明[共著]」\
https://www.morikita.co.jp/books/mid/085531

In [1]:
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
import random

### 入力層について
入力データ：u_data\
入力データの次元：Nu\
中間層(リザバー層)のノード数：Nx\
入力スケーリング, 入力層の結合重み行列：input_scale, w_in\
w_in := -input_scale〜input_scaleの範囲の一様分布に従う乱数\
w_inのshapeは(Nx × Nu)になる。\
→ 重み行列 ? × 入力データ次元 Nu = リザバーの次元(ノード数) Nx \
→ ? = Nx × Nuになる。

In [21]:
def Input(u_data, Nu, Nx, input_scale):
    
    np.random.seed(seed=0)
    w_in = np.random.uniform(-input_scale, input_scale, (Nx,Nu) )
    
    return np.dot(w_in,u_data)

### 確認する
入力データ：5×1\
リザバーノード数：3\
入力結合重み行列：3×5\
出力される結果：3×1

In [22]:
### 入力データの作成
data = np.arange(1,6)

### 二次元データに変換：5 → 5×1
data = data.reshape(-1,1)

### 各パラメータの設定
Nu, Nx = data.shape[0], 3
input_scale = 1

### Input関数実行
Input(data,Nu,Nx,input_scale)

array([[1.17057819],
       [4.93649235],
       [0.22243081]])

### 出力層について
リザバー層からのデータ：x_data\
リザバーのノード数(次元数)：Nx\
出力層のノード数：Ny\
出力スケーリング, 出力層の結合重み行列：output_scale, w_out\
w_out := -output_scale〜output_scaleの範囲の一様分布に従う乱数\
w_outのshapeは(Ny × Nx)になる。\
→ 重み行列 ? × リザバーのノード数 Nx = 出力層のノード数 Ny \
→ ? = Ny × Nxになる。

In [25]:
def Output(x_data, Nx, Ny, output_scale):
    
    np.random.seed(seed=0)
    w_out = np.random.uniform(-output_scale, output_scale, (Ny,Nx) )
    
    return np.dot(w_out,x_data)

### 確認する
出力層のノード数：5×1\
リザバーノード数：3\
出力結合重み行列：5×3\
出力される結果：5×1

In [27]:
### リザバー層からのデータの作成
data = np.arange(1,6)

### 二次元データに変換：5 → 5×1
data = data.reshape(-1,1)

### 各パラメータの設定
Nx, Ny = data.shape[0], 3
input_scale = 1

### Output関数実行
Output(data,Nu,Nx,input_scale)

array([[1.17057819],
       [4.93649235],
       [0.22243081],
       [5.17622675],
       [0.34972478]])

## ==== Appendex ====
### フィードバック層について
出力層からのデータ：y_data\
リザバーのノード数(次元数)：Nx\
出力層からデータ数：Ny\
フィードバックスケーリング, フィードバック層の結合重み行列：fb_scale, w_fb\
w_fb := -fb_scale〜fb_scaleの範囲の一様分布に従う乱数\
w_fbのshapeは(Nx × Ny)になる。\
→ fb重み行列 ? × 出力層のノード数 Ny = リザバー層のノード数 Nx \
→ ? = Nx × Nyになる。

In [28]:
def Feedback(y_data, Nx, Ny, fb_scale):
    
    np.random.seed(seed=0)
    w_fb = np.random.uniform(-fb_scale, fb_scale, (Nx,Ny) )
    
    return np.dot(w_fb,y_data)

### 確認する
リザバー層のノード数：5×1\
出力層のノード数：3\
fb結合重み行列：3×5\
出力される結果：3×1

In [31]:
### 出力層からのデータの作成
data = np.arange(1,6)

### 二次元データに変換：5 → 5×1
data = data.reshape(-1,1)

### 各パラメータの設定
Ny, Nx = data.shape[0], 3
fb_scale = 1

### Output関数実行
Feedback(data,Nx,Ny,fb_scale)

array([[1.17057819],
       [4.93649235],
       [0.22243081]])